art_jobtest_job:
    resource: "@ArtJobtestBundle/Resources/config/routing/job.yml"
    prefix:   /job

art_jobtest_homepage:
    defaults: { _controller: ArtJobtestBundle:Job:index }
    pattern : /

art_jobtest_category:
    pattern : /category/{slug}/{page}
    defaults: { _controller: ArtJobtestBundle:Category:show, page: 1}
