art_jobtest_affiliate:
    resource: "@ArtJobtestBundle/Resources/config/routing/affiliate.yml"
    prefix:   /affiliate

art_jobtest_job:
    resource: "@ArtJobtestBundle/Resources/config/routing/job.yml"
    prefix:   /job

art_jobtest_homepage:
    defaults: { _controller: ArtJobtestBundle:Job:index }
    pattern : /

art_jobtest_category:
    pattern : /category/{slug}/{page}
    defaults: { _controller: ArtJobtestBundle:Category:show, page: 1}
login:
    pattern:   /login
    defaults:  { _controller: ArtJobtestBundle:Default:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
art_jobtest_api:
    pattern: /api/{token}/jobs.{_format}
    defaults: {_controller: ArtJobtestBundle:Api:list}
    requirements:
        _format: xml|json|yaml