imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true
#        collect: false # commented because swift mailer test won't work

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

parameters:
    database_host: 127.0.0.1
    database_port: 3306
    database_name: jobtestcheck
    database_user: jobtest
    database_password: jobtest
